version: '3.8'
services:
    mysql:
        image: mysql:8.0
        container_name: go-mysql-gorm-dev
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'BenIsMe'
            MYSQL_DATABASE: 'go_db_dev'
            MYSQL_USER: 'ben'
            MYSQL_PASSWORD: 'BenIsMe'
        command:
            [
                mysqld,
                --authentication-policy=mysql_native_password,
                --character-set-server=utf8mb4,
                --collation-server=utf8mb4_unicode_ci,
                --innodb_monitor_enable=all,
                --max-connections=1001,
            ]
        volumes:
            - ./mysqldata:/data/db



